### ISSUE TITLE
"Your First Module" Tutorial - rustup wasm32 target

### ISSUE THREAD

**Issue by michaelkacher** [waxosuit/waxosuit-io-site#2]
I have not used Rust before and don't know if this step should be required or not, but in the "Your First Module" Tutorial, I had to run `rustup target add wasm32-unknown-unknown` before I could successfully run `make build`. 

Is this the appropriate way to solve this dependency issue?  Is it due to running on Windows?

If it is correct, I can add a PR if you like.

**Comment by autodidaddict** [comment]
Yeah we do need that target added. I'll make a note of it next time I'm editing that tutorial. Thanks for reporting @michaelkacher
