### ISSUE TITLE
"Your First Module" Tutorial - Error on docker run

### ISSUE THREAD

**Issue by michaelkacher** [waxosuit/waxosuit-io-site#3]
Environment: Windows
rustc version: 1.36.0

Following the "Your First Module" tutorial (https://waxosuit.io/tutorials/firstmod/), `docker make` successfully creates an image.

When running `docker run -e RUST_LOG="info,cranelift_wasm=warn" -p 8080:8080 hello-world` there is an error: "/waxosuit: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory"

Is there any advice on how to approach resolving this?

**Comment by autodidaddict** [comment]
Yes purge your existing local docker image for `waxosuit/waxosuit` and get the latest. There was a bug in the docker image for Waxosuit that didn't include libssl. This is now in the docker image and I've confirmed that the latest one works. Thanks for bringing this up @michaelkacher

**Comment by michaelkacher** [comment]
@autodidaddict I purged the removed the docker image for Waxosuit and pulled it again and I am running into the same issue.  Looking at DockerHub (https://hub.docker.com/r/waxosuit/waxosuit), it appears that the docker image was updated 8 days ago.  Am I using the correct image?  

I appreciate the time.

**Comment by autodidaddict** [comment]
I've got a local docker image that was made 6 days ago, @michaelkacher . I just manually did another push to make sure that the one I have (that works) is the one that's in docker hub. Can you try this again?

Also, what host operating system are you on? I'm using Ubuntu

**Comment by michaelkacher** [comment]
@autodidaddict The new docker image works!  Thank you.

I am on Windows 10, but I had also tried with on WSL 1 and 2 but ran into challenges with cargo generate and not this project so had put it on hold.  If someone testing on Windows 10, WSL 1 or WSL 2 is beneficial, let me know.
